#test1_change
---
# this file assumes Automation Hub is the default source
collections:

- name: community.mysql
  version: 3.3.0
  source: https://galaxy.ansible.com

- name: community.vmware
  version: 1.0.0
  source: https://galaxy.ansible.com

- name: community.general
  version: 2.0.0
  source: https://galaxy.ansible.com

- name: citrix.adc

- name: citrix.adm
