---
- hosts: localhost
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.217
    service_member1_ip: 192.168.2.233
    service_member2_ip: 192.168.2.234

  tasks:
    - name: Setup ssl certkey
      citrix_adc_ssl_certkey:
        nsip: “{{ nsip }}”
        nitro_user: “{{ nitro_user }}”
        nitro_pass: “{{ nitro_pass }}”
        certkey: ansible_created_certirificate
        cert: ansible_created_server.crt
        key: ansible_created_server.key
        expirymonitor: enabled
        notificationperiod: 30
        inform: PEM
        password: False
        passplain: ansible