---
- hosts: all
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.217
    service_member1_ip: 192.168.2.233
    service_member2_ip: 192.168.2.234

  tasks:
  - name: Create a load balancing vserver bound to services
    delegate_to: localhost
    citrix_adc_lb_vserver:
      nsip: “{{ nsip }}”
      nitro_user: “{{ nitro_user }}”
      nitro_pass: “{{ nitro_pass }}”
      validate_certs: no
      state: present
      name: ansible_crated_lb_vserver
      servicetype: HTTP
      timeout: 12
      ipv46: 6.93.3.3
      port: 80
      servicebindings:
          - servicename: ansible-created-service-http-1
            weight: 80
          - servicename: ansible-created-service-http-2
            weight: 20