---
- hosts: localhost
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.217
    service_member1_ip: 192.168.2.233
    service_member2_ip: 192.168.2.234

  tasks:
    - name: Setup lb vserver
      netscaler_lb_vserver:
        nsip: “{{ nsip }}”
        nitro_user: “{{ nitro_user }}”
        nitro_pass: “{{ nitro_pass }}”
        name: lb-vserver-http
        servicetype: SSL
        ipv46: 10.78.0.1
        port: 443
        ssl_certkey: certificate_http
        servicegroupbindings:
        - servicegroupname: service-group-http