---
- hosts: localhost
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.217

  tasks:
    - name: Reset the Password
      citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        nitro_protocol: http
        validate_certs: no
        username: "{{ username }}"
        password: "{{ password }}"
        new_password: "{{ new_password }}"