---
- hosts: all
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.217

  tasks:
    - name: Reset the Password
      citrix.adc.citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        nitro_protocol: http
        validate_certs: no
        username: testuser
        password: testpass
        new_password: "{{ new_password }}"
      delegate_to: localhost
      
    # - name: Rest the Password
    #   uri:
    #     url: https://192.168.2.217/nitro/v1/config/login
    #     method: POST
    #     user: "{{ username }}"
    #     password: "{{ password }}"
    #     force_basic_auth: yes
    #     body_format: json
    #     validate_certs: no
    #     body:
    #       extra_vars:
    #         new_password: "{{ new_password }}"
    #   delegate_to: localhost