---
- hosts: Citrix Device
  gather_facts: false
  collections:
    - citrix.adc

  tasks:
    - name: Reset the Password
      delegate_to: localhost
      citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        nitro_protocol: https
        validate_certs: no