---
- hosts: Citrix Device
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    nsip: 192.168.2.202

  tasks:
    - name: Reset the Password
      delegate_to: localhost
      citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        nitro_protocol: https
        validate_certs: no